server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://rm-wz9pr24uk179wcc41bo.mysql.rds.aliyuncs.com:3306/education_prod_copy?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&useSSL=false&allowMultiQueries=true
    username: root
    password: "@Q86qSv@Ipa#7yW*"
  redis:
    database: 0
    host: 192.168.1.113
    port: 6379
    password: redis
    jedis:
     pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.my_springboot_learn.model
  configuration:
    cache-enabled: true
logging:
  level:
   com:
    example:
     my_springboot_learn:
      mapper: debug

