server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://192.168.1.102:3306/yunjiantest
    username: root
    password: chenyu123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: chenyu123
    jedis:
     pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.my_springboot_learn.model
  configuration:
    cache-enabled: true
logging:
  level:
   com:
    example:
     my_springboot_learn:
      mapper: debug

